defaultContentLanguage = 'es'
baseURL = 'https://buceo.avances123.es'
defaultContentLanguageInSubdir = true
[languages]
  [languages.es]
    languageName = 'Español'
    title = 'Buceo en Cuevas'
    weight = 1
    languageCode = 'es'
  [languages.en]
    languageName = 'English'
    title = 'Cave Diving Spain'
    languageCode = 'en'
    weight = 2
  [languages.fr]
    languageName = 'Français'
    title = 'Plongée souterraine Espagne'
    languageCode = 'fr'
    weight = 3
  [languages.zh]
    languageName = '中文'
    title = '洞穴潜水'
    languageCode = 'zh'
    weight = 4


# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
#disqusShortname = "avances123"

enableRobotsTXT = false
