# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Inicio"
url = "/"
weight = -100
[main.params]
icon = "home"


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/avances123/topografias"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/avances123/"

[social.params]
icon = "brand-instagram"