# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Inicio"
url = "/"
weight = -100
[main.params]
icon = "home"

[[main]]
identifier = "instructor"
name = "Cursos"
url = "https://instructor.avances123.es"
weight = 4
[main.params]
icon = "school"
newtab = true


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/avances123/topografias"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/avances123/"

[social.params]
icon = "brand-instagram"