baseURL = 'https://buceo.avances123.es/'
title = 'Mis apuntes de buceo'
theme = 'rusty-typewriter'

languageCode = 'es'
defaultContentLanguage = "es" 
enableRobotsTXT = true

[params.twitter] 
site = "@avances123"
creator = "@avances123"

# rtwt = Rusty Typewriter Theme
[params.rtwt.side.home]
taxonomies = ['tags']
countTaxonomy = 10

[params.rtwt.side.single]
showAttachments = false
showDetails = false

[related]
 includeNewer = true
 [[related.indices]]
  name = 'tags'
  weight = 100

[rusty_typewriter]
 [params.rtwt]
  sidePane = true
  countPageItems = 20 


[taxonomies]
tag = 'tags'

[params.links]
negocio = 'https://www.sidemount.es'

[params.author]
name = 'Fabio Rueda'
instagram_url = 'https://www.instagram.com/avances123/'

[[menus.main]]
name = 'Cuevas'
pageRef = '/cuevas'
weight = 1

[[menus.main]]
name = 'Articulos'
pageRef = '/articulos'
weight = 2

[[menus.main]]
name = 'Mapas'
pageRef = '/mapas'
weight = 3


[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 4




[markup.goldmark.renderer]
  unsafe = true

# build search index ================
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]
# ===================================
